
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	
	private global::Gtk.Label lblDongle;
	
	private global::Gtk.ComboBox comPorts;
	
	private global::Gtk.Label lblInstructions;
	
	private global::Gtk.Button btnScan;
	
	private global::Gtk.Button btnQuit;
	
	private global::Gtk.Button btnSend;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.Resizable = false;
		this.AllowGrow = false;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblDongle = new global::Gtk.Label ();
		this.lblDongle.Name = "lblDongle";
		this.lblDongle.LabelProp = global::Mono.Unix.Catalog.GetString ("Select dongle:");
		this.fixed1.Add (this.lblDongle);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lblDongle]));
		w1.X = 37;
		w1.Y = 49;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.comPorts = global::Gtk.ComboBox.NewText ();
		this.comPorts.Name = "comPorts";
		this.fixed1.Add (this.comPorts);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.comPorts]));
		w2.X = 125;
		w2.Y = 40;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblInstructions = new global::Gtk.Label ();
		this.lblInstructions.Name = "lblInstructions";
		this.lblInstructions.LabelProp = global::Mono.Unix.Catalog.GetString ("Use a cable to connect TXD and RXD pins on the dongle, then press Test.");
		this.lblInstructions.Wrap = true;
		this.fixed1.Add (this.lblInstructions);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lblInstructions]));
		w3.X = 35;
		w3.Y = 87;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnScan = new global::Gtk.Button ();
		this.btnScan.CanFocus = true;
		this.btnScan.Name = "btnScan";
		this.btnScan.UseUnderline = true;
		this.btnScan.Label = global::Mono.Unix.Catalog.GetString ("Scan");
		this.fixed1.Add (this.btnScan);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnScan]));
		w4.X = 252;
		w4.Y = 41;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnQuit = new global::Gtk.Button ();
		this.btnQuit.CanFocus = true;
		this.btnQuit.Name = "btnQuit";
		this.btnQuit.UseUnderline = true;
		this.btnQuit.Label = global::Mono.Unix.Catalog.GetString ("Quit");
		this.fixed1.Add (this.btnQuit);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnQuit]));
		w5.X = 253;
		w5.Y = 144;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnSend = new global::Gtk.Button ();
		this.btnSend.CanFocus = true;
		this.btnSend.Name = "btnSend";
		this.btnSend.UseUnderline = true;
		this.btnSend.Label = global::Mono.Unix.Catalog.GetString ("Test");
		this.fixed1.Add (this.btnSend);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnSend]));
		w6.X = 210;
		w6.Y = 144;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 503;
		this.DefaultHeight = 534;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
